# Generated by Django 2.2.24 on 2022-01-06 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='openvpn_online_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='VPN账户')),
                ('client_ID', models.CharField(max_length=10, verbose_name='客户端ID')),
                ('remove_add', models.CharField(max_length=15, verbose_name='客户端外网地址')),
                ('virtual_add', models.CharField(max_length=15, verbose_name='VPN分配地址')),
                ('time_online', models.DateTimeField(verbose_name='上线时间')),
                ('offline_time', models.DateTimeField(null=True, verbose_name='下线时间')),
                ('desc', models.CharField(blank=True, default=None, max_length=300, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='openvpn_flow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_flow', models.PositiveIntegerField(verbose_name='上行流量')),
                ('rece_flow', models.PositiveIntegerField(verbose_name='下线流量')),
                ('flow_time', models.DateField(verbose_name='上线时间')),
                ('desc', models.CharField(blank=True, default=None, max_length=300, verbose_name='描述')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openvpn.openvpn_online_user', verbose_name='VPN账户')),
            ],
        ),
    ]
