# Generated by Django 2.2.24 on 2022-01-14 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openvpn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='openvpn_sun_flow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_flow', models.PositiveIntegerField(verbose_name='上行流量')),
                ('rece_flow', models.PositiveIntegerField(verbose_name='下线流量')),
                ('flow_time', models.DateField(verbose_name='传输时间')),
            ],
        ),
        migrations.AlterField(
            model_name='openvpn_flow',
            name='flow_time',
            field=models.DateField(verbose_name='传输时间'),
        ),
    ]
