# Generated by Django 2.2.24 on 2022-01-14 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openvpn', '0002_auto_20220114_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openvpn_flow',
            name='flow_time',
            field=models.DateTimeField(verbose_name='传输时间'),
        ),
    ]
