# Generated by Django 2.2.24 on 2022-01-21 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openvpn', '0004_auto_20220114_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='openvpn_online_user',
            name='vpn_login',
            field=models.BooleanField(default=False, verbose_name='VPN登录标记'),
        ),
    ]
