# Generated by Django 2.2.24 on 2022-02-16 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openvpn', '0007_auto_20220216_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openvpn_flow',
            name='flow_time',
            field=models.CharField(max_length=300, verbose_name='传输时间'),
        ),
    ]
